name: Create Release

on:
  release:
    types:
      - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install-dotnet-sdk:
    name: Install .NET SDK
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: install-dotnet-sdk

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: |
          cd src
          dotnet restore

      - name: Test
        run: |
          cd src
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} --include-symbols --include-source

      - name: Publish Package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate