name: Pull Requests

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, reopened]
    branches:
    - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
